name: Daily Rollup

on:
  schedule:
    - cron: "30 7 * * *"  # 12:30 AM PT = 07:30 UTC
  workflow_dispatch:

jobs:
  rollup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --no-root

      - name: Run daily rollup
        run: |
          poetry run python jobs/daily_rollup.py