name: Feast Materialize

on:
  schedule:
    - cron: "40 10 * * *"     # 03:40 PT nightly, after roll-up
  workflow_dispatch:

concurrency:
  group: feast-materialize
  cancel-in-progress: true

jobs:
  materialize:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Check out the data branch
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: binary-db-updates
      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 2️⃣  Bring in the latest code from main
      - name: Merge main
        run: |
          git fetch origin main
          git merge -X theirs --no-edit origin/main

      # 3️⃣  Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      # 4️⃣  Install deps via Poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          export PATH="$HOME/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          poetry install --no-root

      # 5️⃣  Apply + materialize Feast
      - name: Feast apply & materialize
        run: |
          poetry run feast -c feature_repo apply
          poetry run feast -c feature_repo materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S")

      # 6️⃣  Commit updated registry, if any
      - name: Commit registry update
        run: |
          git add data/feature_registry.db
          git diff --cached --quiet && { echo "No registry change – skipping commit"; exit 0; }
          git commit -m "feat: nightly Feast materialization $(date -u +'%Y-%m-%d')"
          git push --force-with-lease origin HEAD:binary-db-updates
