name: Harvest Queue Times

on:
  schedule:
    - cron: '*/30 15-23 * * *'   # 08:00‑15:30 PT
    - cron: '*/30 0-6 * * *'     # 16:00‑23:30 PT
  workflow_dispatch:

# 🛑 1 job at a time touches the DB
concurrency:
  group: queue-times-db
  cancel-in-progress: true

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Pull the dedicated branch with full history
    - name: Check out binary‑db‑updates
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: binary-db-updates

    # (optional) Fast‑forward the code to match main
    - name: Sync code from main
      run: |
        git fetch origin main
        git merge --ff-only origin/main || echo "::warning ::main diverged; keeping branch version"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install deps
      run: pip install -q requests python-dotenv pandas scikit-learn joblib holidays

    # 2️⃣ Run the script *on this branch* so the DB file changes here
    - name: Harvest queue times
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: python queue_times.py

    - name: Configure Git author
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    # 3️⃣ Commit if anything actually changed
    - name: Commit DB update
      run: |
        git add queue_times.db
        git diff --cached --quiet && { echo "No DB delta ↪ skipping commit"; exit 0; }
        git commit -m "Update SQLite DB: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"

    # 4️⃣ Re‑pull & push (handles rare race where a previous job finished **just** now)
    - name: Rebase & push
      run: |
        git pull --rebase --autostash origin binary-db-updates
        git push --force-with-lease origin HEAD:binary-db-updates