name: Harvest Queue Times

on:
  schedule:
    - cron: "*/30 15-23 * * *"   # 08:00-15:30 PT
    - cron: "*/30 0-6  * * *"    # 17:00-23:30 PT
  workflow_dispatch:

concurrency:
  group: queue-times-db
  cancel-in-progress: true

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the branch that stores data blobs
      - name: Check out binary-db-updates
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: binary-db-updates

      # 2️⃣ Configure Git author (needed for the merge commit below)
      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 3️⃣ Merge latest code from main → brings in pyproject.toml & ingest/
      - name: Sync branch with main
        run: |
          git fetch origin main
          git merge --no-edit origin/main

      # 4️⃣ Debug: show workspace tree – verify ingest/pull_queue_times.py exists
      - name: Debug tree listing
        run: |
          echo "Top-level:"
          ls -al
          echo "-----------"
          echo "ingest folder:"
          ls -al ingest || true
          echo "-----------"

      # 5️⃣ Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 6️⃣ Install Poetry via pip and add it to PATH
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 7️⃣ Install dependencies with Poetry (no package build)
      - name: Install dependencies
        run: |
          python -m poetry install --no-root

      # 8️⃣ Harvest DL & DCA queue times
      - name: Harvest DL & DCA queue times
        run: |
          python -m poetry run python ingest/pull_queue_times.py --park dl
          python -m poetry run python ingest/pull_queue_times.py --park dca

      # 9️⃣ Commit new Parquet parts if any
      - name: Commit data update (if any)
        run: |
          git add data/raw
          git diff --cached --quiet && { echo "No new data – skipping commit"; exit 0; }
          git commit -m "Add hourly Parquet parts: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"

      # 🔟 Rebase & push safely
      - name: Rebase & push
        run: |
          git pull --rebase --autostash origin binary-db-updates
          git push --force-with-lease origin HEAD:binary-db-updates