name: Harvest Queue Times

on:
  # every 30 min while the parks are roughly open (cron = UTC)
  schedule:
    - cron: "*/30 15-23 * * *"     # 08:00‑15:30 PT
    - cron: "*/30 0-6  * * *"      # 17:00‑23:30 PT
  workflow_dispatch:

concurrency:
  group: queue-times-db
  cancel-in-progress: true

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
      ####################################################################
      # 1️⃣  Check out the branch that stores data blobs
      ####################################################################
      - name: Check out binary‑db‑updates
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: binary-db-updates

      ####################################################################
      # 2️⃣  Configure Git author (needed for the merge commit below)
      ####################################################################
      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      ####################################################################
      # 3️⃣  Merge the latest code from main → brings in pyproject & ingest/
      ####################################################################
      - name: Sync branch with main
        run: |
          git fetch origin main
          git merge --no-edit origin/main

      ####################################################################
      # 4️⃣  Debug: show workspace tree – you should see ingest/pull_queue_times.py
      ####################################################################
      - name: Debug tree listing
        run: |
          echo "Top‑level:"
          ls -al
          echo "-----------"
          echo "ingest folder:"
          ls -al ingest || true
          echo "-----------"

      ####################################################################
      # 5️⃣  Set up Python 3.11
      ####################################################################
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      ####################################################################
      # 6️⃣  Install deps via Poetry (no package build)
      ####################################################################
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --no-root

      ####################################################################
      # 7️⃣  Harvest queue‑time data → Parquet
      ####################################################################
      - name: Harvest DL & DCA queue times
        run: |
          poetry run python ingest/pull_queue_times.py --park dl
          poetry run python ingest/pull_queue_times.py --park dca

      ####################################################################
      # 8️⃣  Commit new Parquet parts if any
      ####################################################################
      - name: Commit data update (if any)
        run: |
          git add data/raw
          git diff --cached --quiet && { echo "No new data – skipping commit"; exit 0; }
          git commit -m "Add hourly Parquet parts: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"

      ####################################################################
      # 9️⃣  Rebase & push safely
      ####################################################################
      - name: Rebase & push
        run: |
          git pull --rebase --autostash origin binary-db-updates
          git push --force-with-lease origin HEAD:binary-db-updates