# .github/workflows/harvest.yml
name: Harvest Queue Times

on:
  # every 30 minutes while the parks are (roughly) open in California (cron is UTC)
  schedule:
    - cron: "*/30 15-23 * * *"   # 08:00‑15:30 PT
    - cron: "*/30 0-6 * * *"     # 17:00‑23:30 PT
  workflow_dispatch:

# one job at a time touches the DB
concurrency:
  group: queue-times-db
  cancel-in-progress: true

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣  start directly on the branch that owns the DB
    - name: Check out binary‑db‑updates
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: binary-db-updates

    # 2️⃣  (optional) fast‑forward its code to main
    - name: Sync branch with main (FF only)
      run: |
        git fetch origin main
        git merge --ff-only origin/main || echo "::warning ::main has diverged; leaving branch as‑is"

    # 3️⃣  Python 3.11 — TF wheels exist for this version
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 4️⃣  Install deps from the single source of truth
    - name: Install dependencies
      run: python -m pip install --upgrade -r requirements.txt

    # 5️⃣  Run the harvester (updates queue_times.db)
    - name: Harvest queue‑time data
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: python queue_times.py

    # 6️⃣  Configure Git author
    - name: Configure Git
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    # 7️⃣  Commit only if the DB changed
    - name: Commit DB update (if any)
      run: |
        git add queue_times.db
        git diff --cached --quiet && { echo "No DB change – skipping commit"; exit 0; }
        git commit -m "Update SQLite DB: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"

    # 8️⃣  Rebase in case another job pushed, then push safely
    - name: Rebase & push
      run: |
        git pull --rebase --autostash origin binary-db-updates
        git push --force-with-lease origin HEAD:binary-db-updates