name: Harvest Queue Times

on:
  schedule:
    - cron: '*/30 15-23 * * *'  # 8am–3pm PT
    - cron: '*/30 0-6 * * *'    # 4pm–11pm PT
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      run: python queue_times.py

    - name: Commit and push SQLite DB
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add queue_times.db
        git commit -m "Update SQLite DB: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push